### ISSUE TITLE
Question: Is it possible to use your h5 model with Tensorflow Lite image segmenter?

### ISSUE THREAD

**Issue by stepanov-standy** [aymanKH9991/Hair-Segmentation#1]
Hello, thank you so much for your work. I am looking for a solution for iOS and Android for hair segmentation. I came to your repository and converted h5 to tflite model. But when I try to execute it using the following command line tools, I get this:

`bazel run -c opt  tensorflow_lite_support/examples/task/vision/desktop:image_segmenter_demo --  --model_path=/tmp/hair.tflite  --image_path=$(pwd)/tensorflow_lite_support/examples/task/vision/desktop/g3doc/test.jpg  --output_mask_png=$(pwd)/tensorflow_lite_support/examples/task/vision/desktop/g3doc/segmentation-output.png`

INFO: Build completed successfully, 1 total action
Segmentation failed: The input tensor should have dimensions 1 x height x width x 3. Got 1 x 256 x 256 x 1.

I am new in neural networks, but if I am right image segmenter in tensorflow lite expects 3 channels according to the documentation:
https://www.tensorflow.org/lite/inference_with_metadata/task_library/image_segmenter?hl=ru#model_compatibility_requirements

But converted model has only 1. Is it possible to fix during conversion or I have to train tflite model from scratch? I will really appreciate any help you can provide :) Thanks in advance.

**Comment by ayman-khawaleda** [comment]
Sorry @stepanov-standy I didn't receive your question until now!
I hope You figure it out.
I suggest to You:
1- load the hair segmentation model (architecture and weights )
2- remove the input layer, add new input layer that satisfies your desires 
3- convert the new model to tf-lite model!
4- you should be good to go.
NOTE: the model required GPU!
